baseURL: https://leonie-bick-98.netlify.app/
languageCode: en-us
title: My website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Continue
    subtitle: Data analytics project
    title: Hi, my name is Leonie
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Sussex Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lbick.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Leonie Bick
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
      #  label: Twitter
      #  url: https://www.twitter.com
     # - icon: fa-facebook
     #   label: Facebook
      #  url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/leoniebick/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/leoniebick/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://linkedin.com/in/leonie-bick
  image: ''
  name: Leonie Bick
  navigation:
    button1:
      - name: Contact me
        url: blogs/contact_form
    button2:
      - name: All content
        url: blogs
    links:
      - name: Home
        url: ''
      - name: Personal
        url: blogs/about_me
      - name: Professional
        url: blogs/professional_experience
      #- name: Elements
      #  url: elements.html
    menu: Menu
    subtitle: 
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: cloud-sky-pink-blue.jpg
        subtitle: CLick here to find out more about me
        title: About me
        url: blogs/about_me
      - image: copenhagen.jpg
        subtitle: My first work in R
        title: Started from the bottom...
        url: blogs/LBS_ppa
      - image: ocean.jpg
        subtitle: Our latest data analysis in R
        title: ...now we're here!
        url: blogs/last_project
      - image: dark_ocean.jpg
        subtitle: ...for all aspects of life
        title: Some inspirations 
        url: blogs/ipsum
     # - image: pic05.jpg
      #  subtitle: Ipsum Dolor Sit Amet
       # title: Consequat
        #url: blogs/ipsum
      #- image: pic06.jpg
       # subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/ipsum
  two:
    buttonText: Pssssttttt!
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Some last words
    url: blogs
