baseURL: https://leonie-bick-98.netlify.app/
languageCode: en-us
title: My website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Continue
    subtitle: Welcome to my blog
    title: Hi, my name is Leonie.
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Sussex Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lbick.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Leonie Bick
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
      #  label: Twitter
      #  url: https://www.twitter.com
     # - icon: fa-facebook
     #   label: Facebook
      #  url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/leoniebick/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/leoniebick/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://linkedin.com/in/leonie-bick
  image: ''
  name: Leonie Bick
  navigation:
    #button1:
    #  - name: Contact me
     #   url: blogs/contact_form
    button2:
      - name: All content
        url: blogs
    links:
      - name: Home
        url: ''
      - name: Personal
        url: blogs/about_me
      - name: Professional
        url: blogs/professional_experience
      #- name: Elements
      #  url: elements.html
    menu: Menu
    subtitle: 
    title: Leonie
  tiles:
    enable: yes
    showcase:
      - image: cloud-sky-pink-blue.jpg
        subtitle: CLick here to find out more about me
        title: About me
        url: blogs/about_me
      - image: ocean.jpg
        subtitle: My first work in R
        title: Started from the bottom...
        url: blogs/magnab
      - image: clouds_above.jpg
        subtitle: Our latest data analysis in R
        title: ...now we're here!
        url: blogs/last_project
      - image: dark_ocean.jpg
        subtitle: What defines me
        title: My skills and values 
        url: blogs/skills_values
     # - image: pic05.jpg
      #  subtitle: Ipsum Dolor Sit Amet
       # title: Consequat
        #url: blogs/ipsum
      #- image: pic06.jpg
       # subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/ipsum
  two:
    buttonText: More
    enable: yes
    subtitle: "Thank you for your interest and for taking the time to visit my 
    website. If you have any quetsions or inquiries regarding me or my work, 
    please do not hesitate to reach out on any of my social media channels, via 
    mail or through the contact form below. Have a nice day and speak to you soon!"
    title: Some last words
    url: blogs
